[project]
name = "rpi-wireless-ap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "flask>=3.1.2",
    "jsonify>=0.5",
    "requests>=2.32.5",
]
